# 3D Coordinate Mapping for Mushroom LEDs
# TO BE DEFINED after physical LED installation
# All measurements in feet from origin (center of stem at ground)

mushroom:
  # Physical dimensions
  cap_diameter: 14.0
  cap_height: 7.0    # Height where cap starts
  total_height: 14.0
  stem_diameter: 6.0
  stem_height: 7.0
  
  # Origin point (0, 0, 0) is center of stem at ground level
  # X: left(-) to right(+)
  # Y: back(-) to front(+) 
  # Z: down(-) to up(+)

# LED position mapping will be added after physical installation
# Each LED will get X,Y,Z coordinates based on actual placement