# LED Strip Configuration
# Raspberry Pi 5 with Pi5Neo library
# Physical layout: 700 LEDs across 2 SPI channels

strips:
  - id: stem_interior
    spi_device: "/dev/spidev1.0"  # SPI1 - GPIO 20 (Pin 38)
    led_count: 250
    led_start: 0
    led_end: 249
    location: "mushroom_stem"
    description: "Interior stem lighting for seated viewers"
    
  - id: cap_exterior
    spi_device: "/dev/spidev0.0"  # SPI0 - GPIO 10 (Pin 19)
    led_count: 450
    led_start: 250
    led_end: 699
    location: "mushroom_cap"
    description: "Exterior cap illumination visible from outside"

# Hardware settings for Pi5Neo
hardware:
  spi_speed_khz: 640     # Reduced from 800 to fix "0" bit timing (390ns instead of 312ns)
  brightness: 128        # Global brightness (0-255)
  strip_type: "WS2811"   # LED type
  color_order: "RGB"     # Color order (RGB, GRB, etc.)

# Performance settings  
performance:
  target_fps: 30  # Minimum acceptable FPS
  max_fps: 60     # Target FPS for smooth animations

# Timing parameters (critical for protocol and thread coordination)
timing:
  ws2811_latch_delay_ms: 0.24    # Reset period in milliseconds (min 0.05 for WS2811)
  thread_timeout_ms: 100          # Thread coordination timeout in milliseconds
  max_consecutive_errors: 3       # Errors before thread shutdown
  metrics_window_seconds: 300     # Performance metric rolling window (5 minutes)
  fps_update_interval: 1.0        # How often to calculate FPS (seconds)
  
# Audio settings for reactive patterns
audio:
  enabled: false          # Set to true to enable audio capture
  device: "USB"          # "USB" for auto-detect, or specific device name
  sample_rate: 44100     # Audio sample rate in Hz
  buffer_size: 512       # Audio buffer size in samples
  channels: 1            # Mono input
  gain: 50.0             # Software gain multiplier (increase if mic is too quiet)