# LED Strip Configuration
# Physical layout for 700 LEDs across 4 GPIO pins

strips:
  - id: cap_primary
    gpio_pin: 10  # SPI for best performance
    led_count: 200
    led_start: 0
    led_end: 199
    location: "mushroom_cap"
    description: "Main cap illumination"
    
  - id: cap_secondary  
    gpio_pin: 12  # PWM0
    led_count: 200
    led_start: 200
    led_end: 399
    location: "mushroom_cap"
    description: "Secondary cap illumination"
    
  - id: stem_upper
    gpio_pin: 18  # PWM0
    led_count: 150
    led_start: 400
    led_end: 549
    location: "mushroom_stem"
    description: "Upper stem - visible from entrance"
    
  - id: stem_lower
    gpio_pin: 21  # PWM1
    led_count: 150
    led_start: 550
    led_end: 699
    location: "mushroom_stem"
    description: "Lower stem - ground level"

# Hardware settings
hardware:
  freq_hz: 800000      # WS2811 frequency
  dma_channel: 10      # DMA channel (5 or 10 are safe)
  invert: false        # Signal inversion
  brightness: 128      # Global brightness (0-255)
  strip_type: "WS2811" # LED type
  
# Power settings
power:
  max_current_ma: 20000  # 20A supply
  led_current_ma: 60     # Per LED at full white
  voltage: 5             # Supply voltage

# Performance settings  
performance:
  target_fps: 30
  max_fps: 60
  audio_buffer_size: 64
  audio_sample_rate: 44100