# LED Strip Configuration
# Raspberry Pi 5 with Pi5Neo library
# Physical layout: 700 LEDs across 2 SPI channels

strips:
  - id: stem_interior
    spi_device: "/dev/spidev1.0"  # SPI1 for stem
    led_count: 250
    led_start: 0
    led_end: 249
    location: "mushroom_stem"
    description: "Interior stem lighting for seated viewers"
    
  - id: cap_exterior
    spi_device: "/dev/spidev0.0"  # SPI0 for cap  
    led_count: 450
    led_start: 250
    led_end: 699
    location: "mushroom_cap"
    description: "Exterior cap illumination visible from outside"

# Hardware settings for Pi5Neo
hardware:
  spi_speed_khz: 800     # SPI speed in kHz for WS2811
  brightness: 128        # Global brightness (0-255)
  strip_type: "WS2811"   # LED type
  color_order: "RGB"     # Color order (RGB, GRB, etc.)
  
# Power settings
power:
  max_current_ma: 20000  # 20A supply
  led_current_ma: 60     # Per LED at full white
  voltage: 5             # Supply voltage

# Performance settings  
performance:
  target_fps: 30
  max_fps: 60
  audio_buffer_size: 64
  audio_sample_rate: 44100