# LED Strip Configuration
# Raspberry Pi 5 with Pi5Neo library
# Physical layout: 700 LEDs on single SPI chain (cap first, stem second)

strips:
  - id: cap_exterior
    led_count: 450
    description: "Exterior cap illumination (wired first in chain)"
    
  - id: stem_interior
    led_count: 250
    description: "Interior stem lighting (wired second in chain)"

# Hardware settings for Pi5Neo
hardware:
  spi_device: "/dev/spidev0.0"  # GPIO 10 (Pin 19) - Single SPI chain
  spi_speed_khz: 800     # WS2811 data rate (library multiplies by 8 for SPI clock)
  brightness: 128        # Global brightness (0-255)
  strip_type: "WS2811"   # LED type
  color_order: "RGB"     # Color order (RGB, GRB, etc.)

# Performance settings  
performance:
  target_fps: 30  # Minimum acceptable FPS
  max_fps: 60     # Target FPS for smooth animations

# Timing parameters (critical for protocol and thread coordination)
timing:
  ws2811_latch_delay_ms: 0.24     # Reset period in milliseconds (min 0.05 for WS2811)
  thread_timeout_ms: 100          # Thread coordination timeout in milliseconds
  max_consecutive_errors: 3       # Errors before thread shutdown
  metrics_window_seconds: 300     # Performance metric rolling window (5 minutes)
  fps_update_interval: 1.0        # How often to calculate FPS (seconds)
  
# Audio settings for reactive patterns
audio:
  enabled: false          # Set to true to enable audio capture
  device: "USB"          # "USB" for auto-detect, or specific device name
  sample_rate: 44100     # Audio sample rate in Hz
  buffer_size: 512       # Audio buffer size in samples
  channels: 1            # Mono input
  gain: 50.0             # Software gain multiplier (increase if mic is too quiet)
