# Startup Configuration
# This file controls what pattern and settings are used when the light show starts on boot

# Pattern to load at startup
# Available: test, rainbow_wave, rainbow_cycle
pattern: rainbow_wave

# Global brightness (0-255)
brightness: 128

# Pattern-specific parameters (optional)
pattern_params:
  rainbow_wave:
    wave_length: 100
    speed: 50.0
    saturation: 1.0
  rainbow_cycle:
    cycle_time: 5.0
    saturation: 1.0
  test:
    cycle_time: 3.0

# Performance settings
performance:
  fps_logging: true        # Log FPS every 5 seconds
  log_interval: 5          # Seconds between FPS logs
  
# Audio-reactive settings
audio:
  enabled: false          # Set to true to enable audio input
  device: "USB"          # "USB" for auto-detect, or specific device name
  sensitivity: 0.5       # Audio sensitivity for reactive patterns (0.0-1.0)